### ISSUE TITLE
do you have a reference for the /comments endpoint?

### ISSUE THREAD

**Issue by underchemist** [TheDrHax/Twitch-Chat-Downloader#6]
This isn't an issue with your code or anything. I was just playing with it and was realizing the base_url using /videos/{id}/comments endpoint isn't documented at all at https://dev.twitch.tv/docs/v5

I know v5 is depreciated and will be removed 12/31/2018 but I was wondering if you had seen any documentation for this endpoint and could point me in the right direction.

Cheers

**Comment by TheDrHax** [comment]
I used [this](https://github.com/PetterKraabol/Twitch-Chat-Downloader/issues/23#issuecomment-334568102) comment to fix the script. It contains just enough information to implement a simple client but not more.
